#ifndef __CONFIG_H_
#define __CONFIG_H_

#define IPC_QUEUE_LEN_WATCHDOG        1
#define IPC_QUEUE_LEN_CONTROLLER      2
#define IPC_QUEUE_LEN_INPUT_TOUCH     2
//#define IPC_QUEUE_LEN_DISPLAY         2
//#define IPC_QUEUE_LEN_INPUT_GPIO      1
//#define IPC_QUEUE_LEN_MEASURING       2

#define CONFIG_SUBSCRIBE_MSG_HOOKS 2

#define CFG_TASK_WATCHDOG__POLLING_PERIOD       (300 / portTICK_RATE_MS)
#define CFG_TASK_INPUT_GPIO__POLLING_PERIOD     (1 / portTICK_RATE_MS)
#define CFG_TASK_INPUT_TOUCH__POLLING_PERIOD    (100 / portTICK_RATE_MS)

#endif /* __CONFIG_H_ */
